RyuaNerin/only-stackoverflow

hosts.txt, only-stackoverflow.txt
안녕하세요, RyuaNerin님.
만들어주신 덕분에 개발 관련 검색결과가 깨끗해졌습니다. 감사합니다.
오늘 검색하다 몇 사이트가 더 보여서 추가 해 보았습니다. 확인해보시고 괜찮으면 merge 부탁드립니다.
=> python2.net / answeright.com 추가

hosts.txt, only-stackoverflow.txt
*.i-harness.com --> i-harness.com
맨 앞에 *가 들어가니까 AdGuard 필터가 작동을 안해서 원상복구 했습니다
=> asterisk 수정

hosts.txt, only-stackoverflow.txt
=> ask.roboflow.ai 추가

hosts.txt
http://www.w3bai.com/en-US/index.html
w3schools 짝퉁입니다. 없어서 추가했습니다.
=> add w3schools fake site

only-stackoverflow.tmpl
google.co.kr 별로 안좋아하긴 하지만
google.com 가는거 까먹을 때도 있어서 추가했습니다.
=> Add google.co.kr in filter

hosts.txt
=> Add svcministry.org

hosts.txt
ex)
https://recalll.co/ask/v/topic/javascript-Cancel-event-on-input-type%3D%22file%22/5a86e5ce1126f408028b79dd
original:
https://stackoverflow.com/questions/34855400/cancel-event-on-input-type-file
=> recalll.co 추가

hosts.txt
- origin: https://webmasters.stackexchange.com/questions/1772/how-do-i-set-up-a-cookie-less-domain
- copy1: http://turismocomunitarioguatemala.com/511836
- copy2: http://korean.topgoodhosting.com/drupal/kukigaeopsneun-domein-deurupal-hoseutingeul-sayonghayeo.html
=> turismocomunitarioguatemala.com, topgoodhosting.com 추가

hosts.txt
- origin: https://stackoverflow.com/questions/59269850/caching-apt-packages-in-github-actions-workflow
- copy: https://knews.vip/postcrawl/stack/view?site=so&key=72267648&lang=ko&alias=github-jag-eob-wokeu-peullo-eseo-apt-paekiji-kaesing
=> Add knews.vip

hosts.txt
Shit web site which scrapes github repository's issues
- Original: https://github.com/benmosher/eslint-plugin-import/issues/1552
- Copy: https://bleepcoder.com/ko/eslint-plugin-import/531973444/import-order-not-working-with-types-packages
=> Add bleepcoder.com

README-en.md, README.md
I added a badge on README which leads to filter subscription link, because some people said subscription link is hard to find.
=> Add badge to subscribe filter

hosts.txt
Copy of github issues
ex)
- original: https://github.com/pypa/pip/issues/6433
- copy: https://www.gitmemory.com/issue/pypa/pip/6433/486827293
=> Add `gitmemory.com`

hosts.txt
Copy of wikipedia
- original: https://en.wikipedia.org/wiki/Paulo_Miyao
- copy: https://ko.wikiqube.net/wiki/Paulo_Miyao
=> Add `*.wikiqube.net`

hosts.txt
- Original: https://stackoverflow.com/questions/13708395/how-can-i-draw-a-circle-in-unity3d
- Copy: https://www.it-gundan.com/ko/unity3d/unity3d%EC%97%90%EC%84%9C-%EC%9B%90%EC%9D%84-%EA%B7%B8%EB%A6%AC%EB%A0%A4%EB%A9%B4-%EC%96%B4%EB%96%BB%EA%B2%8C%ED%95%B4%EC%95%BC%ED%95%A9%EB%8B%88%EA%B9%8C/1070456451/
=> Add `it-gundan.com`

hosts.txt
- Original: https://stackoverflow.com/questions/21481682/httpwebrequest-the-underlying-connection-was-closed-the-connection-was-closed/21487464#21487464
- Copy: https://newbedev.com/httpwebrequest-the-underlying-connection-was-closed-the-connection-was-closed-unexpectedly
(FYI: https://meta.stackoverflow.com/questions/410700/is-newbedev-a-copy-of-stack-overflow-questions)
It only copies title and accepted solution (pretty clever)
=> Add `newbedev.com`

hosts.txt
- original: https://stackoverflow.com/questions/12324302/is-it-ok-to-put-a-standard-pure-c-header-include-directive-inside-a-namespace
- copy: https://www.py4u.net/discuss/104954
=> Add `py4u.net`

hosts.txt
[source](https://stackoverflow.com/questions/22384694/sockets-using-inaddr-any-on-client-side)
[copy](https://coderedirect.com/questions/163876/sockets-using-inaddr-any-on-client-side)
=> add `coderedirect.com`

hosts.txt
https://superuser.com/questions/435321
https://itectec.com/superuser/how-to-export-public-keys-in-pem-format-with-gnupg/
완전 그냥 가져왔네요
=> itectec.com 추가

hosts.txt
=> 스택오버플로우 복붙 사이트 추가

hosts.txt
- original: https://stackoverflow.com/questions/4410107/what-is-the-proper-way-to-handle-a-numberformatexception-when-it-is-expected
- copy: https://www.it-gundan.net/ko/java/numberformatexception%EC%9D%B4-%EC%98%88%EC%83%81-%EB%90%A0-%EB%95%8C-%EC%B2%98%EB%A6%AC%ED%95%98%EB%8A%94-%EC%98%AC%EB%B0%94%EB%A5%B8-%EB%B0%A9%EB%B2%95%EC%9D%80-%EB%AC%B4%EC%97%87%EC%9E%85%EB%8B%88%EA%B9%8C/970572403/
Replaced `it-gundan.com` with `it-gundan.*`
=> Add `it-gundan.*`

hosts.txt
티스토리 블로그를 새로 추가했습니다.
이놈의 카피는 사라지질 않네요..
항상 감사하게 사용하고 있어요!
=> Add itsource.tistory.com

hosts.txt
- original: https://stackoverflow.com/questions/70734941/exposed-orm-dsl-vs-dao-in-many-to-many-relationships-best-practices
- copy: https://tutorialmeta.com/question/exposed-orm-dsl-vs-dao-in-many-to-many-relationships-best-practices
=> Add `tutorialmeta.com`

hosts.txt
=> Add intrepidgeeks.com

hosts.txt
=> add `serveanswer.com`

hosts.txt
- original: https://stackoverflow.com/questions/11887799/how-to-mock-new-date-in-java-using-mockito?answertab=scoredesc#tab-top
- copy (1): https://www.javafixing.com/2021/12/fixed-how-to-mock-new-date-in-java.html
- copy (2): https://tousu.in/qa/?qa=559482/
- copy (3): https://catchconsole.com/code-example/how-to-mock-new-date-in-java-using-mockito
- copy (4): https://www.javacodexamples.com/examples/how-to-mock-new-date-in-java-using-mockito
- copy (5): https://exchangetuts.com/how-to-mock-new-date-in-java-using-mockito-1639599784964800
- copy (6): https://ogeek.cn/qa/?qa=559482/ (same shit site of (2))
=> Add multiple sites

hosts.txt
original: https://stackoverflow.com/questions/51686098/release-exoplayer-in-recyclerview
copy: https://androiderrors.com/release-exoplayer-in-recyclerview/
=> 스택오버플로우 복붙사이트 추가

hosts.txt
orig: https://serverfault.com/questions/820306
copy: https://kiwix.ounapuu.ee/serverfault.com_en_all_2019-02/A/question/820306.html
=> Add kiwix.ounapuu.ee

hosts.txt
'How do I run git log to see changes only for a specific branch?' 라는 제목으로 검색했을 때, [stackoverflow](https://stackoverflow.com/questions/4649356/how-do-i-run-git-log-to-see-changes-only-for-a-specific-branch)와 동일한 글을 노출하는 사이트들입니다.
* [intellipaat.com](https://intellipaat.com/community/14434/how-do-i-run-git-log-to-see-changes-only-for-a-specific-branch)
* [rotadev.com](https://rotadev.com/how-do-i-run-git-log-to-see-changes-only-for-a-specific-branch-dev/)
* [idqna.madreview.net](https://idqna.com/question/how-do-i-run-git-log-to-see-changes-only-for-a-specific-branch)
* [jike.in](https://jike.in/qa/?qa=637940/)
* [www.faqcode4u.com](https://www.faqcode4u.com/faq/291767/how-do-i-run-git-log-to-see-changes-only-for-a-specific-branch)
* [qa.overstack.in](https://qa.overstack.in/qa/?qa=637940/) …
=> add 7 hosts

hosts.txt
orig: https://stackoverflow.com/questions/34058825
copy: https://kr.coderbridge.com/questions/131de780f98e42b99253750c84c2c4ca
=> add coderbridge.com

hosts.txt
`es.stackoverflow.com`에서 내용을 퍼와서 영어로 번역기 돌려서 내놓는 사이트를 발견했습니다.
원본 페이지 구글 번역이랑 99% 결과가 동일하더군요...
=> add `holadevs.com`

hosts.txt
=> Add codeproject.com
